[package]
name = "slow-loris"
version = "0.1"
publish = false
edition = "2018"

[dependencies]
tokio = { version = "0.3", features = ["full"] }
futures = "0.3.0"
pretty_env_logger = "0.4.0"
log = "0.4.11"
lazy_static = "1.4.0"

